spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personalbook?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Youngsandy66
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml

